### ISSUE TITLE
Rewrite Usage

### ISSUE THREAD

**Issue by Lytexx** [Lytexx/hollow_memories#10]
https://github.com/Lytexx/hollow_memories#using-youtube-dl

like i mentioned in https://github.com/Lytexx/hollow_memories/issues/5

> i dont like that its explaining every single command most people dont want to copy the whole thing every time

though i meant to say i dont like `how` its explaining every command the format is always Youtube-dl [OPTIONS] URL anyway

so i would like to replace it with a explanation on how to setup the config https://github.com/ytdl-org/youtube-dl#configuration

and then explain the relevant options basically whats already there
https://github.com/ytdl-org/youtube-dl#configuration
https://github.com/Kethsar/ytarchive#usage

but with less commands more in depth and on the topic of archiving streams
as example:

`-o, --output TEMPLATE`
the filename and output path you want to have
if you dont specify an output path it will use the folder you are currently in with cmd
default is `"-o %(title)s-%(id)s.%(ext)s"`
will look like this `NEXT COLOR PLANET _ 星街すいせい-vQHVGXdcqEQ.mp4`

to specify the output path just place the path at the front
-o `"C:/Users/Lytexx/Downloads/%(title)s-%(id)s.%(ext)s"`
you can use ~ to start from your user directory
-o `"~/Downloads/%(title)s-%(id)s.%(ext)s"`
keep in mind that you have to put quotes around it if a foldername has spaces in it or it will break

i recommend using this output template
-o `"[%(upload_date)s] %(title)s [%(uploader)s](%(id)s).%(ext)s"`
will look like this
`[20200322] NEXT COLOR PLANET _ 星街すいせい [Suisei Channel](vQHVGXdcqEQ).mp4`
this is really useful to sort and search for streams

for all options see https://github.com/ytdl-org/youtube-dl#output-template

this may look very complicated but both youtube-dl and ytarchive work fine without adding any commands to it
we can provide a good default that should work for most people
example for ytarchive 
`python ytarchive.py --threads 4 --vp9 -w --add-metadata -t -o "[%(upload_date)s] %(title)s [%(channel)s](%(id)s)"`
Will use 4 threads for downloading
 vp9 if its available
 wait for a stream if its scheduled
 add metadata and thumbnail
and use `[%(upload_date)s] %(title)s [%(channel)s](%(id)s)` as filename template

Relevant Options for Youtube-dl would be: (not in this order)
```--ignore-config
--config-location
--match-filter
-r, --limit-rate
--fragment-retries
--hls-use-mpegts
--external-downloader
--external-downloader-args
-a, --batch-file
-o, --output
--write-description
--write-info-json
--load-info-json
--cookies
--write-thumbnail
-g, --get-url
--sleep-interval
--max-sleep-interval
-f, --format
-F, --list-formats
--merge-output-format
--write-sub
--all-subs
--sub-format
-x, --extract-audio
--embed-subs
--embed-thumbnail
--add-metadata

**Comment by ghost** [comment]
Can you check if I'm heading the right direction in my [rewrite branch](https://github.com/fourilent/hollow_memories/tree/rewrite)? 
I'm not able to write a guide for setting up a default config for youtube-dl as I lack experience with the program, would be great if you could write a draft for me to polish.

**Comment by Lytexx** [comment]
> Can you check if I'm heading the right direction in my [rewrite branch](https://github.com/fourilent/hollow_memories/tree/rewrite)?

yes looks good 👍 

> I'm not able to write a guide for setting up a default config for youtube-dl as I lack experience with the program, would be great if you could write a draft for me to polish.

its really simple https://github.com/ytdl-org/youtube-dl#configuration

> On Windows, the user wide configuration file locations are %APPDATA%\youtube-dl\config.txt
or C:\Users\<user name>\youtube-dl.conf. Note that by default configuration file may not exist so you may need to create it yourself.

if the config exists in one of those 2 places it will always use it without having to specify anything

if its somewhere else we need to use --config-location
--config-location "C:\Users\Lytexx\Downloads\config.txt" as example

old yt-dl config from me im using a different one for yt-dlp
```
-o "~/Downloads/[%(upload_date)s] %(title)s [%(uploader)s].%(ext)s"

--external-downloader-args "-loglevel fatal -stats -m3u8_hold_counters 25"

--format "bestvideo[vcodec *= vp9]+bestaudio[ext=m4a]/bestvideo+bestaudio/best"
--merge-output-format "mp4"

#add Metadata
--add-metadata

#add Thumbnail
--embed-thumbnail

**Comment by Lytexx** [comment]
https://github.com/Lytexx/hollow_memories/commit/45894189276402078d0f14724d6334f7669a0d6b
