### ISSUE TITLE
Add Linux Scripts to /scripts

### ISSUE THREAD

**Issue by Kazandu** [Lytexx/hollow_memories#13]
Add bash scripts to the scripts section. I know, some stuff might not work on every platform but i prepared an example with dlentireschannel.bat , working on a standard debian 10 machine which should be a solid baseline and should work for most people.
I cant attach .sh's here so i'll uploaded it to gist https://gist.github.com/Kazandu/866009e1c5dee47a53c15e0f3b2cfa8d , if you want to i can convert the other scripts too.

**Comment by Lytexx** [comment]
i made a folder for linux scripts and added your example
https://github.com/Lytexx/hollow_memories/tree/master/scripts/Linux

you can add the rest with a pull request or upload them somewhere so i can add them

**Comment by Lytexx** [comment]
seems like you forgot about this so i will close it for now
feel free to make a pr if you still want to do it
