### ISSUE TITLE
Rewrite archiving_livestreams.md

### ISSUE THREAD

**Issue by Lytexx** [Lytexx/hollow_memories#3]
Streamlink and Youtube-dl are terrible for recording ongoing livestreams

ytarchive is as long as it gets updated the best way to do it
just replacing it with a simple howto should be enough since its way less complex
https://github.com/Kethsar/ytarchive

**Comment by ghost** [comment]
working on it

**Comment by Lytexx** [comment]
https://github.com/Lytexx/hollow_memories/commit/45894189276402078d0f14724d6334f7669a0d6b
