### ISSUE TITLE
Guide for content sharing

### ISSUE THREAD

**Issue by Lytexx** [Lytexx/hollow_memories#4]
Nyaa.si is the best site to share hololive related torrents
i have a lot of experience for it so i will try writing this part

for cloud storage i only tried mega.nz and gofile.io
so i think it would be better if someone else takes this part

**Comment by Kazandu** [comment]
The G Workspace trick could be added too, if people have access to it they could use the unlimited space on the Shared Drive to share files too. But this is limited to people who either have a business account from work or are willing to pay ~10€ per month to create one themselves

**Comment by Lytexx** [comment]
partly added in https://github.com/Lytexx/hollow_memories/commit/ece8ee1474bd7e66ae09d03d780c3e3bf7902059
nyaa.si part is unnecessary imo I might add it again in the future but i think this is fine for now
