### ISSUE TITLE
Rewrite/Move FixingShortVideoError.md

### ISSUE THREAD

**Issue by Lytexx** [Lytexx/hollow_memories#6]
The video is downloading fine im assuming it wasnt fully processed when he added it

downloading videos over dash almost always results in a broken video file
i want to delete this and make it a section in the readme instead when we have enough information on why this exactly happens

**Comment by ghost** [comment]
The issue is identified as per https://github.com/Lytexx/hollow_memories/pull/9#issuecomment-803558209
Are there any workarounds to this issue or do we just wait for an official fix?

**Comment by Lytexx** [comment]
> The issue is identified as per [#9 (comment)](https://github.com/Lytexx/hollow_memories/pull/9#issuecomment-803558209)
> Are there any workarounds to this issue or do we just wait for an official fix?

i doubt ffmpeg will ever fix this the only workaround is using h264 instead of vp9 when its only available over dash
> using 299+140 would work but using 303+251 will result in a broken file

`-S "proto"` will prefer https over dash

**Comment by Lytexx** [comment]
Now that i think about it using -S "proto" should be the default it just "prefers" it so if there is only dash it will still download the video

**Comment by Lytexx** [comment]
https://github.com/Lytexx/hollow_memories/commit/45894189276402078d0f14724d6334f7669a0d6b
